Fix problem with publish callback invoked twice
mqttjs/MQTT.js pull request #1635
Opened 2023-07-12 05:59 UTC by ogis-yamazaki

The following modification prevents the callback from invoked twice.

- If ``resonCode`` in PUBACK to failure, set the cb variable to NULL after the callback is invoked.
- When deleting a message from the store, do not invoke the callback if cb is null 

Related issue: #1511

2023-07-12 06:18 UTC, robertsLando requested changes
Thanks for the PR @ogis-yamazaki ! Would you mind to add a unit test that covers this?

2023-07-12 06:18 UTC, robertsLando commented on lib/client.js
> +          cb = null
```suggestion
          // prevent invoking callback twice when deleting message from store #1635
          cb = null
```

2023-07-12 10:28 UTC, ogis-yamazaki commented
@robertsLando 

Added qos 1 and qos2 tests.

When an error occurs in PUBREC, added a process to remove the message from the ``outgoingStore``.

2023-07-12 11:39 UTC, robertsLando approved these changes
LGTM

2023-07-12 11:49 UTC, robertsLando reviewed
By checking the code on my side I saw that this: 

```
delete this.outgoing[messageId]
      this.outgoingStore.del(packet, cb)
      this.messageIdProvider.deallocate(messageId)
      this._invokeStoreProcessingQueue()
```

Is used 3 times in the code. Would you mind to create a dedicated function for that?

2023-07-13 03:22 UTC, ogis-yamazaki commented
@robertsLando 

> Is used 3 times in the code. Would you mind to create a dedicated function for that?

OK

> I see we also have a method removeOutgoingMessage, it doesn't call _invokeStoreProcessingQueue and messageIdProvider.deallocate maybe that's an error too?

As you said, additional processing was needed.

In ``removeOutgoingMessage``, needs to call messageIdProvider.deallocate.
If not called, the messageId will be in use forever.

``_invokeStoreProcessingQueue`` must also be called.
Normally, ``_invokeStoreProcessingQueue`` is called when a PUBACK or similar event occurs, but ``removeOutgoingMessage`` will not pass through it.
The ``_storeProcessingQueue`` may remain unprocessed.

The ``_invokeStoreProcessingQueue`` function also seems to have an implementation problem.

There is a problem if ``_invokeStoreProcessingQueue`` is called while the store is resending(_storeProcessing = true).
Specifically, Message overtaking may occur.
It is necessary to modify the content of _storeProcessingQueue`` so that it is not processed during resend(_storeProcessing = true).

2023-07-13 06:55 UTC, robertsLando commented
Would you mind to also fix those errors or do you prefer to do that in a separeted PR?

2023-07-13 10:42 UTC, ogis-yamazaki commented
@robertsLando 

> Would you mind to also fix those errors or do you prefer to do that in a separeted PR?

Fixed in this PR.

2023-07-14 07:17 UTC, robertsLando approved these changes
LGTM, now everything is much cleaner. Thanks @ogis-yamazaki 🙏🏼

2023-07-14 07:18 UTC, merged