fix: replace `duplexify` with nodejs `Duplex`
mqttjs/MQTT.js pull request #1732
Opened 2023-11-08 10:47 UTC by robertsLando

Fixes #1647

2023-11-09 08:12 UTC, robertsLando commented
@mcollina We actually use `duplexify` in `ws` `wsx` and `ali` protocols. If I understood it correctly, on browsers we do this:

1. Create the websocket `const socket = createBrowserWebSocket(client, opts)`. This is the connection to our broker
2. Create a proxy `const proxy = buildProxy(opts, socketWriteBrowser, socketEndBrowser)`. Proxy is a Transform stream used to ensure data written to socket is a Buffer and not a string (when opts.objectMode is not true).
3. If the socket is open we return the `proxy` as `stream`, if not we create a duplex using duplexify and when the socket is open we set proxy as duplex readable and writeable. The only reason I found to do this is that duplexify, when no readable and writeable are set, buffers all writes and flush them when `setWritable` is called.

If all my suppositions are correct I would like to know how in your opinion I could use readable-stream `Duplex` to replace duplexify. In my idea I could simply create a util class like:


```ts
export class BufferedDuplex extends Duplex {
	public socket: WebSocket

	public proxy: Transform

	public eventListenerSupport: boolean

	public socketOpen: boolean

	private isReadyPromise: Promise<void>

	private resolveReady: () => void

	constructor(opts: IClientOptions, proxy: Transform, socket: WebSocket) {
		super({
			objectMode: true,
		})
		this.proxy = proxy
		this.socket = socket
		this.eventListenerSupport =
			typeof socket.addEventListener !== 'undefined'

		if (!opts.objectMode) {
			this._writev = writev
		}

		this.socketOpen = false

		this.isReadyPromise = new Promise((resolve) => {
			this.resolveReady = resolve
		})

		function onOpen() {
			this.socketOpen = true
			this.resolveReady()
			this.emit('connect')
		}

		if (this.eventListenerSupport) {
			socket.addEventListener('open', onOpen)
		} else {
			socket.onopen = onOpen
		}

		this.on('end', () => {
			this.proxy.end()
		})
	}

	_read(size?: number): void {
		this.proxy.read(size)
	}

	async _write(chunk: any, encoding: string, cb: (err?: Error) => void) {
		if (!this.socketOpen) {
			// wait for socket to open
			await this.isReadyPromise
		}

		this.proxy.write(chunk, encoding, cb)
	}

	_final(callback: (error?: Error) => void): void {
		this.proxy.end(callback)
	}
}
```

2023-11-09 09:58 UTC, robertsLando commented on src/lib/connect/ws.ts
> -				buffers[i] = Buffer.from(chunks[i], 'utf8')
I also noticed this should have been `chunks[i].chunk`. Wondering how this cold ever be working before. Corrected [here](https://github.com/mqttjs/MQTT.js/pull/1732/files#diff-c807a1a5cf80c9f0c9fd037f1173b6e0beefe3672e805ff1392ef3be225858c7R15)

2023-11-09 10:00 UTC, robertsLando commented on src/lib/connect/ws.ts
> +} from 'isomorphic-ws'
This is a nice package that automatically uses ws on node and global.Websocket on browser. This makes types more clear

2023-11-09 10:02 UTC, robertsLando commented
cc @vishnureddy17 if you also would like to give a look at this your feedback would be welcome :)

2023-11-09 10:44 UTC, robertsLando commented on src/lib/connect/ws.ts
>  	function socketWriteBrowser(
Wondering if there should be a return after setTimeout [here](https://github.com/mqttjs/MQTT.js/pull/1732/files#diff-cc6fb47ee82c471804f56a0629299e3e03381c08ce37d2b3053c259badf7fa64L265) ?

2023-11-09 10:58 UTC, robertsLando commented on src/lib/connect/ws.ts
> +		proxy._writev = writev.bind(proxy)
Wondering how this could have work before without the `bind`, maybe Transform automatically handles the bind the `_writev` is set?

2023-11-09 13:46 UTC, vishnureddy17 commented
I like the changes. Unfortunately, my knowledge on Streams in JS is poor, so I don't think my review will be of much use.

I share your concerns regarding:
- lack of `bind` on `writev` before
- the `chunks[i].chunk` issue
- return after the `setTimeout` in `socketWriteBrowser`

2023-11-09 14:06 UTC, robertsLando commented on src/lib/connect/ws.ts
> +			return
Wondering if there should be a return after setTimeout [here](https://github.com/mqttjs/MQTT.js/pull/1732/files#diff-cc6fb47ee82c471804f56a0629299e3e03381c08ce37d2b3053c259badf7fa64L265) ?

Seems it should: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/bufferedAmount

2023-11-09 18:20 UTC, robertsLando commented
Seems that the reason why socket error in browser are not triggering client error is that the error emitted doesn't contain a code that is recognized as a socket error code, in fact it is a generic window [Event](https://developer.mozilla.org/en-US/docs/Web/API/Event), seems that we could get a code in close event but that [will always be 1006](https://stackoverflow.com/a/28396165) (see [reference](https://datatracker.ietf.org/doc/html/rfc6455#section-7.4.1). The fix could be to emit the error with a static code, maybe ECONREFUSED so that will trigger the error on client and close the connection, this will remove the need to call destroy on stream.

2023-11-11 17:12 UTC, getlarge reviewed
As i have no knowledge of the MQTTjs codebase, i only reviewed BufferedDuplex and its usage in ws.ts.
I'll keep on reading ...but here is my firs thought.

2023-11-11 18:29 UTC, robertsLando commented on src/lib/BufferedDuplex.ts
> +	async _write(chunk: any, encoding: string, cb: (err?: Error) => void) {
That's the first way I implemented it (I mean by using a queue) but preferred this solution as it doesn't require another variable. Not sure if making the method async makes any difference, the underlying code handling stream expects it to be sync so will never await it anyway (also unhandled rejections are impossible)

2023-11-13 08:40 UTC, robertsLando commented
@mcollina kindly ping

2023-11-16 09:24 UTC, mcollina requested changes

2023-11-16 09:51 UTC, robertsLando commented on src/lib/BufferedDuplex.ts
> +	async _write(chunk: any, encoding: string, cb: (err?: Error) => void) {
@mcollina Ok, fixed now 🙏🏼

2023-11-17 10:46 UTC, robertsLando commented
@mcollina ping

2023-11-18 07:56 UTC, mcollina approved these changes
lgtm

2023-11-18 08:25 UTC, merged