increase help-me version to fix vulnerability in glob/inflight
mqttjs/MQTT.js pull request #1773
Opened 2024-01-09 17:25 UTC by jackbridger

Closes #1770 
I incremented in package json but should I also include package-lock.json?
Also, the tests were timing out when I ran them (also before I made changes)

2024-01-10 07:50 UTC, robertsLando commented
@jackbridger You should run npm install help-me@5.0.0 instead, that will also update package-lock

2024-01-10 07:50 UTC, robertsLando requested changes
Missing package-lock update, use npm install

2024-01-10 12:46 UTC, jackbridger commented
Made the change, let me know if I should change anything else. Also thanks for your help.

2024-01-23 14:12 UTC, robertsLando approved these changes

2024-01-23 14:13 UTC, merged