fix(react-native): error Cannot create URL for blob
mqttjs/MQTT.js pull request #1840
Opened 2024-04-10 13:43 UTC by MaximoLiberata

# Error: Cannot create URL for blob!

**located**: src/lib/client.ts
 **method**: _setupPingTimer
  **class**: PingTimer
   **init**: getTimer(variant) = getTimer('auto')

## Description:

The error is caused for the library `worker-timers` when the class `PingTimer` call `getTimer('auto')` method. This method `getTimer` doesn't recognize it's executed in ReactNative (RN), it know it's executed in a browser, but RN implements its own timers as: `setTimeOut`, `setInterval`, etc., when is called the method `workerTimer` instead `nativeTimer` the library `worker-timers` that implement `Blob` to store data or whatever it does, throw the next error: **[Error: cannot create URL for blob!]**, `Blob` it isn't supported by RN.

## Fix:

To support ReactNative (RN) it's necessary install 2 package additionals to RN projects:

- [buffer](https://www.npmjs.com/package/buffer)
- [url](https://www.npmjs.com/package/url)

Also include the next code at beginning of the program:

`
process.nextTick = (callback) => {
	setTimeout(callback, 0)
}
`

## Conclusion

I have the commit of the fix of this bug, please @robertsLando allow me create a PR and show you my solution.

I will attach my mqtt client connection and the files I changed in this package to fix the bug:

[mqtt_client_example.txt](https://github.com/mqttjs/MQTT.js/files/14898370/mqtt_client_example.txt)
[is-browser.txt](https://github.com/mqttjs/MQTT.js/files/14898380/is-browser.txt)
[get-timer.txt](https://github.com/mqttjs/MQTT.js/files/14898379/get-timer.txt)
[shared.txt](https://github.com/mqttjs/MQTT.js/files/14898381/shared.txt)
[BufferedDuplex.txt](https://github.com/mqttjs/MQTT.js/files/14898382/BufferedDuplex.txt)

2024-04-10 13:50 UTC, robertsLando requested changes

2024-04-10 13:50 UTC, robertsLando commented on src/lib/get-timer.ts
> +
Cannot this be:

```
return isBrowser && !isWebWorker &&  !isReactNativeBrowser ? workerTimer : nativeTimer
```

2024-04-10 14:01 UTC, MaximoLiberata commented on src/lib/get-timer.ts
> +
Yes, could be, let me change it.

2024-04-10 14:05 UTC, robertsLando submitted a review, later dismissed

2024-04-10 14:06 UTC, robertsLando commented
@MaximoLiberata Please fix lint issues: `npm run lint-fix`

2024-04-10 14:07 UTC, MaximoLiberata commented on src/lib/get-timer.ts
> +
I changed it, check it out

2024-04-10 14:38 UTC, robertsLando approved these changes

2024-04-10 14:39 UTC, merged

2024-04-12 17:51 UTC, abdelhameedhamdy commented
Hey @MaximoLiberata
thanks for issue resolving, wonder should 
```process.nextTick = (callback) => { setTimeout(callback, 0) }```

still to be added at start of the program, after the recent release 5.5.2, 
As without adding this line, I got process.nextTick  is not a function error in RN app.

Thanks

2024-04-12 19:27 UTC, MaximoLiberata commented
> Hey @MaximoLiberata thanks for issue resolving, wonder should `process.nextTick = (callback) => { setTimeout(callback, 0) }`
> 
> still to be added at start of the program, after the recent release 5.5.2, As without adding this line, I got process.nextTick is not a function error in RN app.
> 
> Thanks

Hey @abdelhameedhamdy,

Yes, it's still necessary add that line at start of the program, the library doesn't affect the global environment of the React Native APP, also I couldn't find what library/package is using process.nextTick . I gonna upload a example of my RN implementation where you and other can see it and test it.

2024-04-12 20:42 UTC, abdelhameedhamdy commented
> > Hey @MaximoLiberata thanks for issue resolving, wonder should `process.nextTick = (callback) => { setTimeout(callback, 0) }`
> > still to be added at start of the program, after the recent release 5.5.2, As without adding this line, I got process.nextTick is not a function error in RN app.
> > Thanks
> 
> Hey @abdelhameedhamdy,
> 
> Yes, it's still necessary add that line at start of the program, the library doesn't affect the global environment of the React Native APP, also I couldn't find what library/package is using process.nextTick . I gonna upload a example of my RN implementation where you and other can see it and test it.

I think the package is  ```process-nextick-args```

2024-04-12 23:10 UTC, MaximoLiberata commented
> > > Hey @MaximoLiberata thanks for issue resolving, wonder should `process.nextTick = (callback) => { setTimeout(callback, 0) }`
> > > still to be added at start of the program, after the recent release 5.5.2, As without adding this line, I got process.nextTick is not a function error in RN app.
> > > Thanks
> > 
> > 
> > Hey @abdelhameedhamdy,
> > Yes, it's still necessary add that line at start of the program, the library doesn't affect the global environment of the React Native APP, also I couldn't find what library/package is using process.nextTick . I gonna upload a example of my RN implementation where you and other can see it and test it.
> 
> I think the package is `process-nextick-args`

I will see it and I will return you a feedback, while please check the implementation that I did in React Native [(React Native MQTT.js Implementation)](https://github.com/MaximoLiberata/react-native-mqtt.js-example), test it and tell me if worked for you, also to continue the discussion you can go to [#1841](https://github.com/mqttjs/MQTT.js/discussions/1841)