fix: add option to reconnect if connack has an error code
mqttjs/MQTT.js pull request #1948
Opened 2024-10-16 14:50 UTC by mgabeler-lee-6rs

fixes #1947

WIP:
- [ ] Not sure about the naming of the new option
- [ ] New option defaulting disabled to avoid surprise in consumers, but there's an argument to defaulting it on
- [ ] Needs tests

2024-10-16 15:15 UTC, robertsLando reviewed
The option name looks good to me. Remember to add tests and also docs

2024-11-14 07:56 UTC, robertsLando commented
@mgabeler-lee-6rs I still don't understand why ci fails, could you try removing the test and push? Just to see if that's the reason

2024-11-21 16:44 UTC, mgabeler-lee-6rs commented
Trying that, but somehow I suspect that the problem is more likely related to building/uploading from a fork?

2024-11-21 16:50 UTC, robertsLando requested changes

2024-11-21 16:56 UTC, mgabeler-lee-6rs commented
Was going to suggest contacting codecov for help, but I noticed this is using the nodejs uploader, which is deprecated to the point that the repo is archived

2024-11-21 17:08 UTC, robertsLando commented
That's what I tried here: https://github.com/mqttjs/MQTT.js/pull/1943 

But no clue why when I add that action workflow remains in wait state for no reason

2024-11-21 17:39 UTC, mgabeler-lee-6rs commented
checks on that PR show:
> Annotations
> 1 error
> [Error](https://github.com/mqttjs/MQTT.js/actions/runs/11812893939/workflow)
codecov/codecov-action@v4 is not allowed to be used in mqttjs/MQTT.js. Actions in this workflow must be: within a repository owned by mqttjs, created by GitHub, or matching the following: mqttjs-test, npm-publish, release-it, semantic-pr, amannn/action-semantic-pull-request@*.

2024-11-22 08:08 UTC, robertsLando commented
Oh god you thanks sooo much for that! I think I lost 4 hours trying to debug that and I totally forgot we have some restrictions on actions that can run.... Could you tell me where you got those errors? I wan't able to see them

2024-11-22 08:12 UTC, robertsLando commented on test/abstract_client.ts
> +			})
Try to remove skip now, also I think you can remove server.close as it's handled by teardown

2024-11-22 09:22 UTC, robertsLando commented
Ok I fixed tests and did a minor refactor, could you please fix conflicts? I moved all tests under `test/node` folder for consistency

2024-11-22 14:16 UTC, mgabeler-lee-6rs commented
> Could you tell me where you got those errors? I wan't able to see them

I clicked into the Checks tab on the PR, and from there (on one of the older commits that failed), into the `MQTT.js Tests` on the left bar, which had a :left_speech_bubble: icon, which takes me to a page like https://github.com/mqttjs/MQTT.js/actions/runs/11968792492 which has that error at the bottom under the `Annotations` header.

> could you please fix conflicts?

On it!

2024-11-26 15:28 UTC, merged